<?php

/**
 * @file
 * Module used to embed meta tags in the HEAD for use in indexing in Google
 * Scholar and Zotero.
 */

/**
 * Creates meta tags to be placed in the head of the HTML.
 *
 * @param AbstractObject $object
 *   A AbstractObject.
 *
 * @return array
 *   Associative array where the key is the name of the tag and the value is
 *   the content.
 */
function islandora_google_scholar_create_meta_tags($object) {
  // Need at least title, full name of at least one author which may be a corporate author, publication year.
  module_load_include('inc', 'islandora_multilingual', 'includes/Multilingual');
  $datastream = chooseLanguage($object, 'MODS-');
  if (!$datastream || !islandora_datastream_access(FEDORA_VIEW_OBJECTS, $object[$datastream])) {
    return FALSE;
  }
  else {
    $tags = array();
    $tags['citation_author'] = array();
    $mods = $object[$datastream]->content;
    $mods_xml = new SimpleXMLElement($mods);
    $mods_xml->registerXPathNamespace('mods', 'http://www.loc.gov/mods/v3');

    $title_results = $mods_xml->xpath('/mods:mods/mods:titleInfo/mods:title');
    $title = (string) reset($title_results);

    if (!empty($title)) {
      $tags['citation_title'] = $title;
    }
    else {
      return FALSE;
    }

    $authors = array();

    foreach ($mods_xml->name as $name_xml) {
      $name_parts = array();
      $role = (string) @$name_xml->role->roleTerm;
      if ($role) {
        if ($role == 'Author' || $role == 'aut') {
          foreach ($name_xml->namePart as $name_part) {
            if ((string) $name_part != '') {
              // Strip periods off the end.
              $np = (string) rtrim($name_part, '.');
              if ($name_part['type'] == 'given') {
                $name_parts['first_name'] = (string) $name_part;
              }
              if ($name_part['type'] == 'family') {
                $name_parts['last_name'] = $np;
              }
              if ($name_part['type'] == Null) {
                $name_parts['direct'] = $np;
              }
            }
          }
        }
        if (isset($name_parts['last_name']) && isset($name_parts['first_name'])) {
          $tags['citation_author'][] = $name_parts['last_name'] . ', ' . $name_parts['first_name'];
        }
        elseif (isset($name_parts['direct'])) {
          $tags['citation_author'][] = $name_parts['direct'];
        }
      }
    }
    if (count($tags['citation_author']) == 0) {
      // Check for contributors...
        foreach ($mods_xml->name as $name_xml) {
          $name_parts = array();
          $role = (string) @$name_xml->role->roleTerm;
          if ($role) {
            if ($role == 'Contributor' || $role == 'ctb') {
              foreach ($name_xml->namePart as $name_part) {
                if ((string) $name_part != '') {
                  $np = (string) rtrim($name_part, '.');
                  if ($name_part['type'] == 'given') {
                    $name_parts['first_name'] = (string) $name_part;
                  }
                  if ($name_part['type'] == 'family') {
                    $name_parts['last_name'] = $np;
                  }
                  if ($name_part['type'] == Null) {
                    $name_parts['direct'] = $np;
                  }
                }
              }
            }
            if (isset($name_parts['last_name']) && isset($name_parts['first_name'])) {
              $tags['citation_author'][] = $name_parts['last_name'] . ', ' . $name_parts['first_name'];
            }
            elseif (isset($name_parts['direct'])) {
              $tags['citation_author'][] = $name_parts['direct'];
            }
          }
        }
    }
    if (count($tags['citation_author']) == 0) {
      return FALSE;
    }

    $origin_date = $mods_xml->xpath('//mods:originInfo/mods:dateIssued');
    $part_date = $mods_xml->xpath('//mods:part/mods:date');
    $related_date = $mods_xml->xpath('//mods:relatedItem[@type="host"]//mods:date');
    $created_date = $mods_xml->xpath('//mods:originInfo/mods:dateCreated');

    if ($origin_date) {
      $date = (string) reset($origin_date);
    }
    elseif ($part_date) {
      $date = (string) reset($part_date);
    }
    elseif ($related_date) {
      $date = (string) reset($related_date);
    }
    elseif ($created_date) {
      $date = (string) reset($created_date);
    }
    else {
      return FALSE;
    }

    // Google requires dates in yy/mm/dd format or just the year. As dates suck
    // and we don't have a consistent structure of input we will just return the
    // year for now.
    if ($date) {
      $date_obj = new DateTime($date);
      $date_string = date_format($date_obj, 'Y');
      $tags['citation_publication_date'] = $date_string;
    }

    $journal_title = $mods_xml->xpath('//mods:relatedItem[@type="host"]//mods:title');
    if ($journal_title) {
      $tags['citation_journal_title'] = (string) reset($journal_title);
    }

    $volume = $mods_xml->xpath('//mods:part/mods:detail[@type="volume"]/mods:number');
    if ($volume) {
      $tags['citation_volume'] = (string) reset($volume);
    }

    $issn = $mods_xml->xpath('//mods:identifier[@type="issn"]');
    if ($issn) {
      $tags['citation_issn'] = str_replace(
          array("&", "=", ",", ";"),
          array('', '', '', ''),
          (string) reset($issn));
    }

    $isbn = $mods_xml->xpath('//mods:identifier[@type="isbn"]');
    if ($isbn) {
      $tags['citation_isbn'] = str_replace(
          array("&", "=", ",", ";"),
          array('', '', '', ''),
          (string) reset($isbn));
    }

    $issue = $mods_xml->xpath('//mods:part/mods:detail[@type="issue"]/mods:number');
    if ($issue) {
      $tags['citation_issue'] = (string) reset($issue);
    }

    $start_page = $mods_xml->xpath('//mods:extent[@unit="page"]/mods:start');
    if ($start_page) {
      $tags['citation_firstpage'] = (string) reset($start_page);
    }

    $end_page = $mods_xml->xpath('//mods:extent[@unit="page"]/mods:end');
    if ($end_page) {
      $tags['citation_endpage'] = (string) reset($end_page);
    }

    $online_date = $mods_xml->xpath('//mods:recordInfo/mods:recordCreationDate');
    if ($online_date) {
      $date = (string) reset($online_date);
      $date_obj = new DateTime($date);
      $date_string = date_format($date_obj, 'Y');
      $tags['citation_online_date'] = $date_string;
    }

    $doi = $mods_xml->xpath('//mods:identifier[@type="doi"]');
    if ($doi) {
      $tags['citation_doi'] = (string) reset($doi);
    }

    $publisher = $mods_xml->xpath('//mods:originInfo/mods:publisher');
    if ($publisher) {
        $tags['DC.publisher'] = (string) reset($publisher);
    }

    if ($object['OBJ-EN']) {
      $tags['citation_pdf_url'][] = url("islandora/object/$object->id/datastream/OBJ-EN/view", array('absolute' => TRUE));
    }
    if ($object['OBJ-ES']) {
      $tags['citation_pdf_url'][] = url("islandora/object/$object->id/datastream/OBJ-ES/view", array('absolute' => TRUE));
    }
    if ($object['OBJ-FR']) {
      $tags['citation_pdf_url'][] = url("islandora/object/$object->id/datastream/OBJ-FR/view", array('absolute' => TRUE));
    }

    $tags['citation_abstract_html_url'] = url("islandora/object/$object->id/", array('absolute' => TRUE));
  }

  return $tags;
}

/**
 * Adds the meta tags to the HEAD of the html document.
 *
 * @param array $tags
 *   An associate array containing the name => content of the meta tags.
 */
function islandora_google_scholar_embed_tags($tags) {
  if ($tags != FALSE) {
    foreach ($tags as $name => $content) {
      if (is_array($content)) {
        foreach ($content as $key => $nested_val) {
          $element = array(
            '#tag' => 'meta',
            '#attributes' => array(
              'name' => $name,
              'content' => htmlspecialchars($nested_val),
            ),
          );
          drupal_add_html_head($element, $key . '_' . $nested_val);
        }
      }
      else {
        $element = array(
          '#tag' => 'meta',
          '#attributes' => array(
            'name' => $name,
            'content' => htmlspecialchars($content),
          ),
        );
        drupal_add_html_head($element, $name);
      }
    }
  }
}

/**
 * Implements hook_CMODEL_islandora_view_object().
 */
function islandora_google_scholar_islandora_CEC_multilingual_islandora_view_object($object) {
  $tags = islandora_google_scholar_create_meta_tags($object);
  islandora_google_scholar_embed_tags($tags);
}
